//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ImageUrl { get; set; }
        public bool InStock { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int Quantity { get; set; }
        public byte[] ProductImage { get; set; }

        public virtual Categories Categories { get; set; }
    }
}
