//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingDetails
    {
        public int ShoppingDetailId { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Addres { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string PaymentType { get; set; }
        public string Client_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
